### ISSUE TITLE
Find email Problem

### ISSUE THREAD

**Issue by reihsr** [BBMRI-ERIC/negotiator.bbmri#40]
05 Jan 2021 15:15:41,218 ERROR eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilPerson (DatabaseUtilPerson.java:55) - 8ed18878-DatabaseUtilPerson ERROR-NG-0000073: Error get person with emailAddress:

**Comment by reihsr** [comment]
05 Jan 2021 15:15:41,219 ERROR eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilPerson (DatabaseUtilPerson.java:56) - context
org.jooq.exception.TooManyRowsException: Cursor returned more than one result
	at org.jooq.impl.Utils.fetchOne(Utils.java:1179) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:445) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:397) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2392) ~[jooq-3.6.4.jar:?]
	at eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilPerson.getPersonIdByEmailAddress(DatabaseUtilPerson.java:52) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.sendAggregatedNotifications(NotificationScheduledExecutor.java:44) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.run(NotificationScheduledExecutor.java:25) [classes/:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_222]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_222]
05 Jan 2021 15:15:41,309 ERROR eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilNotification (DatabaseUtilNotification.java:46) - 882e8cb6-DbUtilNotification ERROR-NG-0000030: Error add Notification Entry for notificationType: 9, requestId: 0, commentId: 0, personId: null.
05 Jan 2021 15:15:41,309 ERROR eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilNotification (DatabaseUtilNotification.java:49) - context
org.jooq.exception.DataAccessException: SQL [insert into "public"."notification" ("query_id", "comment_id", "person_id", "notification_type", "create_date") values (?, ?, ?, ?, cast(? as timestamp)) returning "public"."notification"."notification_id"]; ERROR: null value in column "person_id" violates not-null constraint
  Detail: Failing row contains (1508, 0, 0, null, AGGREGATED_NOTIFICATION, 2021-01-05 15:15:41.268).
	at org.jooq.impl.Utils.translate(Utils.java:1646) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:176) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:142) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:138) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:185) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123) ~[jooq-3.6.4.jar:?]
	at eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilNotification.addNotificationEntry(DatabaseUtilNotification.java:43) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.NotificationService.createNotificationEntry(NotificationService.java:95) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.NotificationService.sendNotification(NotificationService.java:27) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.aggregatedNotification(NotificationScheduledExecutor.java:60) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.sendAggregatedNotifications(NotificationScheduledExecutor.java:45) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.run(NotificationScheduledExecutor.java:25) [classes/:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_222]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_222]
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "person_id" violates not-null constraint
  Detail: Failing row contains (1508, 0, 0, null, AGGREGATED_NOTIFICATION, 2021-01-05 15:15:41.268).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:83) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:376) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342) ~[jooq-3.6.4.jar:?]
	... 18 more

**Comment by reihsr** [comment]
05 Jan 2021 15:15:41,316 ERROR eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification (NotificationAggregatedNotification.java:36) - 9389e532970f-NotificationAggregatedNotification ERROR-NG-0000071: Error in NotificationAggregatedNotification.
05 Jan 2021 15:15:41,316 DEBUG org.jooq.tools.JooqLogger (JooqLogger.java:255) - Executing query          : update "public"."mail_notification" set "status" = ?, "send_date" = cast(? as timestamp) where "public"."mail_notification"."mail_notification_id" = ?
05 Jan 2021 15:15:41,316 ERROR eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification (NotificationAggregatedNotification.java:37) - context
java.lang.NullPointerException: null
	at eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification.setContact(NotificationAggregatedNotification.java:43) ~[classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification.run(NotificationAggregatedNotification.java:32) [classes/:?]

**Comment by reihsr** [comment]
05 Jan 2021 16:15:43,534 ERROR eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification (NotificationAggregatedNotification.java:36) - 9389e532970f-NotificationAggregatedNotification ERROR-NG-0000071: Error in NotificationAggregatedNotification.
05 Jan 2021 16:15:43,533 ERROR eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilNotification (DatabaseUtilNotification.java:207) - context
org.jooq.exception.DataAccessException: SQL [update "public"."mail_notification" set "status" = ?, "send_date" = cast(? as timestamp) where "public"."mail_notification"."mail_notification_id" = ?]; ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.jooq.impl.Utils.translate(Utils.java:1646) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:133) ~[jooq-3.6.4.jar:?]
	at eu.bbmri.eric.csit.service.negotiator.database.DatabaseUtilNotification.updateMailNotificationEntryStatus(DatabaseUtilNotification.java:202) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.updateNotificationInDatabase(NotificationScheduledExecutor.java:74) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.aggregatedNotification(NotificationScheduledExecutor.java:62) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.sendAggregatedNotifications(NotificationScheduledExecutor.java:45) [classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.util.NotificationScheduledExecutor.run(NotificationScheduledExecutor.java:25) [classes/:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_222]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_222]
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412) ~[postgresql-9.3-1102-jdbc41.jar:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:410) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:276) ~[jooq-3.6.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342) ~[jooq-3.6.4.jar:?]
	... 8 more
05 Jan 2021 16:15:43,534 ERROR eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification (NotificationAggregatedNotification.java:37) - context
java.lang.NullPointerException: null
	at eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification.setContact(NotificationAggregatedNotification.java:43) ~[classes/:?]
	at eu.bbmri.eric.csit.service.negotiator.notification.types.NotificationAggregatedNotification.run(NotificationAggregatedNotification.java:32) [classes/:?]
